Updated Dockerfile to use a specific Alpine version and modified entrypoint.sh to enhance functionality.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,6 +8,15 @@ jobs:
     steps:
       - uses: actions/checkout@v4.1.1
       - name: Run my own container action
+        id: my-action
         uses: ./
         with:
           who-to-greet: '@jrrpedersen'
+      - name: Output the answer
+        run: echo "The answer is ${{ steps.my-action.outputs.answer }}"
+        # Fail the CI build when an unexpected result is returned from the Docker container action
+      - name: Test the container
+        if: ${{ steps.my-action.outputs.answer != 42 }}
+        run: |
+          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
+          exit 1
